### ISSUE TITLE
Unable to see below me

### ISSUE THREAD

**Issue by Megawallcreeper** [Project-Vyre/Finality-Genesis#4]
I have been playing this modpack for about 12 hours now but looking down is extremely frustrating. When I do so I just either see my armor semi Infront of me but have managed using chainmail to help with the vision in order to look straight down I see the inside of my skin and can't see anything below me. I wanted to turn my skin off entirely, but I don't know what mod or where to do it inside settings. I apologize if this is a stupid issue to write about, but I would love some help with this. Thank you.
![Screenshot 2023-09-07 152713](https://github.com/Project-Vyre/Finality-Genesis/assets/144384509/2aea60b9-4a0e-4d22-8e1e-b25686a58cf1)

**Comment by CelestialAbyss** [comment]
Apologies for the late response:

Simply press F6 to disable the first person model created by Real Camera.

**Comment by Megawallcreeper** [comment]
> Apologies for the late response:
> 
> Simply press F6 to disable the first person model created by Real Camera.

Thank you this has helped so much. Have a wonderful day.
